-- Record of hotfix applied 2026-09-10 via API (already applied to remote).
-- Dashboard slippage & yield kosong: data ada di SQLite lokal tapi tidak
-- pernah di-sync (sync hanya kirim 4 tabel). Safe to re-run: CREATE TABLE
-- IF NOT EXISTS tidak ada — pakai guard DO block agar idempotent.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'paper_slippage_log') THEN
    CREATE TABLE public.paper_slippage_log (
      id           bigint generated by default as identity primary key,
      timestamp    text not null,
      pair         text not null,
      bid          real,
      ask          real,
      mid          real,
      spread_pct   real not null,
      UNIQUE(timestamp, pair)
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'paper_yield_log') THEN
    CREATE TABLE public.paper_yield_log (
      date         text primary key,
      cash_before  real not null,
      rate_daily   real not null,
      amount       real not null
    );
  END IF;
END
$$;

ALTER TABLE public.paper_slippage_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paper_yield_log ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read access on paper_slippage_log') THEN
    CREATE POLICY "Public read access on paper_slippage_log" ON public.paper_slippage_log
      FOR SELECT TO public USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role can insert paper_slippage_log') THEN
    CREATE POLICY "Service role can insert paper_slippage_log" ON public.paper_slippage_log
      FOR INSERT TO public WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read access on paper_yield_log') THEN
    CREATE POLICY "Public read access on paper_yield_log" ON public.paper_yield_log
      FOR SELECT TO public USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role can insert paper_yield_log') THEN
    CREATE POLICY "Service role can insert paper_yield_log" ON public.paper_yield_log
      FOR INSERT TO public WITH CHECK (true);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_paper_slippage_pair ON public.paper_slippage_log(pair);
