-- Record of hotfix applied 2026-09-10 via API (already applied to remote).
-- Root cause board duplikat: sync mengirim positions TANPA id sementara
-- route upsert onConflict=id → tiap sync INSERT baris identity baru.
-- Safe to re-run: DELETE no-op tanpa duplikat, SET GENERATED idempotent,
-- constraint guarded by IF NOT EXISTS.

DELETE FROM public.paper_positions a
USING public.paper_positions b
WHERE a.id > b.id
  AND a.pair = b.pair
  AND a.entry_date = b.entry_date
  AND a.status = b.status;

ALTER TABLE public.paper_positions ALTER COLUMN id SET GENERATED BY DEFAULT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'paper_positions_pair_entry_uniq'
  ) THEN
    ALTER TABLE public.paper_positions
      ADD CONSTRAINT paper_positions_pair_entry_uniq UNIQUE (pair, entry_date);
  END IF;
END
$$;
